### ISSUE TITLE
Code Integration

### ISSUE THREAD

**Issue by mikeshams** [jamesmchacko/Capstone-Project_G2#12]
Demonstrate the task!

**Comment by ChristyRachel** [comment]
Still we have issues with our GPS Module sir

**Comment by ChristyRachel** [comment]
Hi sir, we got the output. Because of bad weather, we were not getting output in GPS. But now we got the output, and we recorded it as a video. We are adding that video to the following link. The connection image link is also adding after that.  https://github.com/jamesmchacko/Capstone-Project_G2/blob/main/Code_Integrated_Output_Demonstration%20(1).mp4
https://github.com/jamesmchacko/Capstone-Project_G2/blob/main/Connection_Image-min.jpeg
